name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Write service account JSON
        shell: bash
        env:
          SA_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOLDENBELLAI_D2605 }}
        run: |
          echo "$SA_JSON" > ${HOME}/gcp-sa.json
          echo "Wrote service account to ${HOME}/gcp-sa.json"

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy with firebase-tools
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/gcp-sa.json
        run: |
          firebase --project goldenbellai-d2605 hosting:sites:list || true
          firebase deploy --only hosting --project goldenbellai-d2605 --non-interactive

